# Generated by Django 3.2 on 2022-05-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emahei', '0008_auto_20220525_1415'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20220525_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_examination', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_examination', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('passmark', models.IntegerField()),
                ('fullmark', models.IntegerField()),
                ('Rules', models.TextField()),
                ('Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emahei.standard')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emahei.subject')),
            ],
            options={
                'verbose_name_plural': 'Examination',
            },
        ),
        migrations.CreateModel(
            name='Mcqestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_no', models.IntegerField()),
                ('Question', models.CharField(blank=True, max_length=500, null=True)),
                ('Option_A', models.CharField(blank=True, max_length=500, null=True)),
                ('Option_B', models.CharField(blank=True, max_length=500, null=True)),
                ('Option_C', models.CharField(blank=True, max_length=500, null=True)),
                ('Option_D', models.CharField(blank=True, max_length=500, null=True)),
                ('Answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20)),
                ('name_of_examination', models.ManyToManyField(to='exam.Examination')),
            ],
            options={
                'verbose_name_plural': 'Mcqestion',
            },
        ),
        migrations.CreateModel(
            name='Type_of_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_examination', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Type_of_exam',
            },
        ),
        migrations.CreateModel(
            name='Student_Exam_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('Question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.mcqestion')),
                ('name_of_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examination')),
                ('name_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student_Exam_Record',
            },
        ),
    ]
