# Generated by Django 3.2 on 2022-05-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emahei', '0008_auto_20220525_1415'),
        ('exam', '0002_auto_20220525_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='Standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emahei.standard'),
            preserve_default=False,
        ),
    ]
