# Generated by Django 3.2 on 2022-05-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_examination_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqestion',
            name='name_of_examination',
        ),
        migrations.AddField(
            model_name='mcqestion',
            name='name_of_examination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.examination'),
            preserve_default=False,
        ),
    ]
