# Generated by Django 3.2 on 2022-05-25 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0004_auto_20220525_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Answer_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('Question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.mcqestion')),
                ('name_of_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examination')),
                ('name_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student_Answer_record',
            },
        ),
        migrations.CreateModel(
            name='Student_Paper_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_answered', models.CharField(blank=True, max_length=10, null=True)),
                ('correct_answered', models.CharField(blank=True, max_length=10, null=True)),
                ('mark_optained', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.mcqestion')),
                ('name_of_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examination')),
                ('name_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student_Answer_record',
            },
        ),
        migrations.DeleteModel(
            name='Student_Exam_Record',
        ),
    ]
