# Generated by Django 3.2 on 2022-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emahei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='offerprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
