# Generated by Django 3.2 on 2022-05-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('emahei', '0003_auto_20220522_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.school'),
        ),
    ]
