# Generated by Django 3.2 on 2022-05-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('emahei', '0004_alter_liveclass_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.school'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emahei.subject'),
        ),
    ]
