# Generated by Django 3.2 on 2022-05-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emahei', '0009_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': 'Notice'},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='name',
            new_name='notice',
        ),
    ]
