# Generated by Django 3.2 on 2022-07-16 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emahei', '0010_auto_20220526_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student_name',
            field=models.ManyToManyField(blank=True, related_name='classtakingteacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
