# Generated by Django 3.2 on 2022-05-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enotes',
            name='school',
        ),
    ]
