# Generated by Django 3.2 on 2022-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_of_publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
