# Generated by Django 3.2 on 2022-06-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220525_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_profile',
            options={'verbose_name_plural': 'Student_Profile'},
        ),
    ]
